.build:
  tags:
    - python3
    - bazel
    - gcc-arm-embedded
  stage: build
  script:
    - bazel build //examples/...:all

build-freebsd:
  extends: .build
  tags:
    - freebsd

build-linux:
  extends: .build
  tags:
    - linux
